# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/serranovexx-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/serranovexx-common/proprietary/etc/B05QL_s5k5e3yx_module_info.xml:vendor/etc/B05QL_s5k5e3yx_module_info.xml \
    vendor/samsung/serranovexx-common/proprietary/etc/Bluetooth_cal.acdb:vendor/etc/Bluetooth_cal.acdb \
    vendor/samsung/serranovexx-common/proprietary/etc/F13QS_imx135_module_info.xml:vendor/etc/F13QS_imx135_module_info.xml \
    vendor/samsung/serranovexx-common/proprietary/etc/General_cal.acdb:vendor/etc/General_cal.acdb \
    vendor/samsung/serranovexx-common/proprietary/etc/Global_cal.acdb:vendor/etc/Global_cal.acdb \
    vendor/samsung/serranovexx-common/proprietary/etc/H08QL_s5k4h5yb_module_info.xml:vendor/etc/H08QL_s5k4h5yb_module_info.xml \
    vendor/samsung/serranovexx-common/proprietary/etc/Handset_cal.acdb:vendor/etc/Handset_cal.acdb \
    vendor/samsung/serranovexx-common/proprietary/etc/Hdmi_cal.acdb:vendor/etc/Hdmi_cal.acdb \
    vendor/samsung/serranovexx-common/proprietary/etc/Headset_cal.acdb:vendor/etc/Headset_cal.acdb \
    vendor/samsung/serranovexx-common/proprietary/etc/Speaker_cal.acdb:vendor/etc/Speaker_cal.acdb \
    vendor/samsung/serranovexx-common/proprietary/lib/hw/camera.vendor.msm8916.so:vendor/lib/hw/camera.vendor.msm8916.so \
    vendor/samsung/serranovexx-common/proprietary/lib/hw/sensors.vendor.msm8916.so:vendor/lib/hw/sensors.vendor.msm8916.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libAl_Awb.so:vendor/lib/libAl_Awb.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libAl_Awb_Sp.so:vendor/lib/libAl_Awb_Sp.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libaec_algo_front.so:vendor/lib/libaec_algo_front.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libaec_algo_rear.so:vendor/lib/libaec_algo_rear.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libaf_algo_rear.so:vendor/lib/libaf_algo_rear.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libawb_algo_front_al.so:vendor/lib/libawb_algo_front_al.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libawb_algo_rear_al.so:vendor/lib/libawb_algo_rear_al.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libsec-ril.so:vendor/lib/libsec-ril.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libsensor.so:vendor/lib/libsensor.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libyasalgo.so:vendor/lib/libyasalgo.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libdiag.so:vendor/lib/libdiag.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libdsi_netctrl.so:vendor/lib/libdsi_netctrl.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libdsutils.so:vendor/lib/libdsutils.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libidl.so:vendor/lib/libidl.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmipl.so:vendor/lib/libmmipl.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmjpeg.so:vendor/lib/libmmjpeg.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmqjpeg_codec.so:vendor/lib/libmmqjpeg_codec.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libqcci_legacy.so:vendor/lib/libqcci_legacy.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libqmi.so:vendor/lib/libqmi.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libqmi_cci.so:vendor/lib/libqmi_cci.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libqmi_client_qmux.so:vendor/lib/libqmi_client_qmux.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libqmi_common_so.so:vendor/lib/libqmi_common_so.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libqmi_csi.so:vendor/lib/libqmi_csi.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libqmi_encdec.so:vendor/lib/libqmi_encdec.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libqmiservices.so:vendor/lib/libqmiservices.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libqomx_jpegenc.so:vendor/lib/libqomx_jpegenc.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libarcsoft_night_shot.so:vendor/lib/libarcsoft_night_shot.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libarcsoft_panorama_burstcapture.so:vendor/lib/libarcsoft_panorama_burstcapture.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libarcsoft_picaction.so:vendor/lib/libarcsoft_picaction.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libarcsoft_selfie_camera_lite.so:vendor/lib/libarcsoft_selfie_camera_lite.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libarcsoft_sensorndk.so:vendor/lib/libarcsoft_sensorndk.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libarcsoft_wideselfie.so:vendor/lib/libarcsoft_wideselfie.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libmmcamera_cac2_lib.so:vendor/lib/libmmcamera_cac2_lib.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libmmcamera_wavelet_lib.so:vendor/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/serranovexx-common/proprietary/lib/libmmcamera2_stats_algorithm.so:vendor/lib/libmmcamera2_stats_algorithm.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libactuator_dw9804_kleos_camcorder.so:vendor/lib/libactuator_dw9804_kleos_camcorder.so \
        vendor/samsung/serranovexx-common/proprietary/vendor/lib/libactuator_dw9804_kleos_camera.so:vendor/lib/libactuator_dw9804_kleos_camera.so \
        vendor/samsung/serranovexx-common/proprietary/vendor/lib/libactuator_dw9804_e5_camcorder.so:vendor/lib/libactuator_dw9804_e5_camcorder.so \
        vendor/samsung/serranovexx-common/proprietary/vendor/lib/libactuator_dw9804_e5_camera.so:vendor/lib/libactuator_dw9804_e5_camera.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_hdr_lib.so:vendor/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_imx219.so:vendor/lib/libmmcamera_imx219.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_rohm_brce064gwz_eeprom.so:vendor/lib/libmmcamera_rohm_brce064gwz_eeprom.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_s5k4ecgx.so:vendor/lib/libmmcamera_s5k4ecgx.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_s5k5e3yx.so:vendor/lib/libmmcamera_s5k5e3yx.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_silicon_sr544_eeprom.so:vendor/lib/libmmcamera_silicon_sr544_eeprom.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_sr030pc50.so:vendor/lib/libmmcamera_sr030pc50.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_sr130pc20.so:vendor/lib/libmmcamera_sr130pc20.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_sr200pc20.so:vendor/lib/libmmcamera_sr200pc20.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_sr544.so:vendor/lib/libmmcamera_sr544.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_tintless_algo.so:vendor/lib/libmmcamera_tintless_algo.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:vendor/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:vendor/lib/libmmcamera_hdr_gb_lib.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_image_stab.so:vendor/lib/libmmcamera_image_stab.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_imglib.so:vendor/lib/libmmcamera_imglib.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_s5k4h5yb.so:vendor/lib/libmmcamera_s5k4h5yb.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_s5k6a3yx.so:vendor/lib/libmmcamera_s5k6a3yx.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_c2d_module.so:vendor/lib/libmmcamera2_c2d_module.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_cpp_module.so:vendor/lib/libmmcamera2_cpp_module.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:vendor/lib/libmmcamera2_frame_algorithm.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_is.so:vendor/lib/libmmcamera2_is.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_iface_modules.so:vendor/lib/libmmcamera2_iface_modules.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:vendor/lib/libmmcamera2_imglib_modules.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_isp_modules.so:vendor/lib/libmmcamera2_isp_modules.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:vendor/lib/libmmcamera2_pproc_modules.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:vendor/lib/libmmcamera2_sensor_modules.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_stats_modules.so:vendor/lib/libmmcamera2_stats_modules.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_vpe_module.so:vendor/lib/libmmcamera2_vpe_module.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera2_wnr_module.so:vendor/lib/libmmcamera2_wnr_module.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/liboemcamera.so:vendor/lib/liboemcamera.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_dw_dw9806b_eeprom.so:vendor/lib/libmmcamera_dw_dw9806b_eeprom.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_imx135.so:vendor/lib/libmmcamera_imx135.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libmmcamera_lsi_s5k5e3yx_eeprom.so:vendor/lib/libmmcamera_lsi_s5k5e3yx_eeprom.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_imx219_common.so:vendor/lib/libchromatix_imx219_common.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_imx219_common_res0.so:vendor/lib/libchromatix_imx219_common_res0.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_imx219_default_video.so:vendor/lib/libchromatix_imx219_default_video.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_imx219_liveshot.so:vendor/lib/libchromatix_imx219_liveshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_imx219_panorama.so:vendor/lib/libchromatix_imx219_panorama.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_imx219_preview.so:vendor/lib/libchromatix_imx219_preview.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_imx219_snapshot.so:vendor/lib/libchromatix_imx219_snapshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_imx219_zslshot.so:vendor/lib/libchromatix_imx219_zslshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_common.so:vendor/lib/libchromatix_s5k4h5yb_common.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_common_res0.so:vendor/lib/libchromatix_s5k4h5yb_common_res0.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_common_res1.so:vendor/lib/libchromatix_s5k4h5yb_common_res1.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_default_video.so:vendor/lib/libchromatix_s5k4h5yb_default_video.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_liveshot.so:vendor/lib/libchromatix_s5k4h5yb_liveshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_panorama.so:vendor/lib/libchromatix_s5k4h5yb_panorama.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_preview.so:vendor/lib/libchromatix_s5k4h5yb_preview.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_snapshot.so:vendor/lib/libchromatix_s5k4h5yb_snapshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_video_hd.so:vendor/lib/libchromatix_s5k4h5yb_video_hd.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_zsl.so:vendor/lib/libchromatix_s5k4h5yb_zsl.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k4h5yb_zslshot.so:vendor/lib/libchromatix_s5k4h5yb_zslshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_common.so:vendor/lib/libchromatix_s5k5e3yx_common.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_pip.so:vendor/lib/libchromatix_s5k5e3yx_pip.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_preview.so:vendor/lib/libchromatix_s5k5e3yx_preview.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_snapshot.so:vendor/lib/libchromatix_s5k5e3yx_snapshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_video.so:vendor/lib/libchromatix_s5k5e3yx_video.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_vt.so:vendor/lib/libchromatix_s5k5e3yx_vt.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_vt_hd.so:vendor/lib/libchromatix_s5k5e3yx_vt_hd.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_zslshot.so:vendor/lib/libchromatix_s5k5e3yx_zslshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_common.so:vendor/lib/libchromatix_s5k6a3yx_common.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_default_video.so:vendor/lib/libchromatix_s5k6a3yx_default_video.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_preview.so:vendor/lib/libchromatix_s5k6a3yx_preview.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_snapshot.so:vendor/lib/libchromatix_s5k6a3yx_snapshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_s5k6a3yx_zsl.so:vendor/lib/libchromatix_s5k6a3yx_zsl.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_sr544_common.so:vendor/lib/libchromatix_sr544_common.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_sr544_default_video.so:vendor/lib/libchromatix_sr544_default_video.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_sr544_preview.so:vendor/lib/libchromatix_sr544_preview.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_sr544_snapshot.so:vendor/lib/libchromatix_sr544_snapshot.so \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libchromatix_sr544_zslshot.so:vendor/lib/libchromatix_sr544_zslshot.so \
    vendor/samsung/serranovexx-common/proprietary/bin/qseecomd:vendor/bin/qseecomd \
    vendor/samsung/serranovexx-common/proprietary/vendor/lib/libQSEEComAPI.so:vendor/lib/libQSEEComAPI.so