# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j3ltectc/setup-makefiles.sh

# ACDB
PRODUCT_COPY_FILES += \
    vendor/samsung/j3ltectc/proprietary/etc/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Bluetooth_cal.acdb \
    vendor/samsung/j3ltectc/proprietary/etc/General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/General_cal.acdb \
    vendor/samsung/j3ltectc/proprietary/etc/Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Global_cal.acdb \
    vendor/samsung/j3ltectc/proprietary/etc/Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Handset_cal.acdb \
    vendor/samsung/j3ltectc/proprietary/etc/Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Hdmi_cal.acdb \
    vendor/samsung/j3ltectc/proprietary/etc/Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Headset_cal.acdb \
    vendor/samsung/j3ltectc/proprietary/etc/Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Speaker_cal.acdb

# Camera
PRODUCT_COPY_FILES += \
    vendor/samsung/j3ltectc/proprietary/etc/B05QL_s5k5e3yx_module_info.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/B05QL_s5k5e3yx_module_info.xml \
    vendor/samsung/j3ltectc/proprietary/etc/L08QL_s5k4h5yc_module_info.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/L08QL_s5k4h5yc_module_info.xml \
    vendor/samsung/j3ltectc/proprietary/lib/hw/camera.vendor.msm8916.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.vendor.msm8916.so \
    vendor/samsung/j3ltectc/proprietary/lib/libaec_algo_front.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaec_algo_front.so \
    vendor/samsung/j3ltectc/proprietary/lib/libaec_algo_rear.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaec_algo_rear.so \
    vendor/samsung/j3ltectc/proprietary/lib/libaf_algo_rear.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaf_algo_rear.so \
    vendor/samsung/j3ltectc/proprietary/lib/libAl_Awb.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libAl_Awb.so \
    vendor/samsung/j3ltectc/proprietary/lib/libAl_Awb_Sp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libAl_Awb_Sp.so \
    vendor/samsung/j3ltectc/proprietary/lib/libawb_algo_front_al.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libawb_algo_front_al.so \
    vendor/samsung/j3ltectc/proprietary/lib/libawb_algo_rear_al.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libawb_algo_rear_al.so \
    vendor/samsung/j3ltectc/proprietary/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera2_stats_algorithm.so \
    vendor/samsung/j3ltectc/proprietary/lib/libmmcamera_cac2_lib_13M.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_cac2_lib_13M.so \
    vendor/samsung/j3ltectc/proprietary/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/j3ltectc/proprietary/lib/libTsAlsc.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libTsAlsc.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libactuator_dw9804_e5_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9804_e5_camcorder.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libactuator_dw9804_e5_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9804_e5_camera.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libactuator_dw9807_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9807_camcorder.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libactuator_dw9807_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9807_camera.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_common_res0.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_common_res0.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_common_res1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_common_res1.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_common.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_default_video.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_liveshot.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_panorama.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_preview.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_snapshot.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_sports.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_sports.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_video_hd.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_zslshot.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k4h5yc_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yc_zsl.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_common.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_pip.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_pip.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_preview.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_snapshot.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_video.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt_30fps.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_vt_30fps.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_vt_hd.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_vt.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_zslshot.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_dw_dw9807_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dw_dw9807_eeprom.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_gb_lib.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_image_stab.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_image_stab.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_pdafcamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdafcamif.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdaf.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_s5k4h5yc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k4h5yc.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_s5k5e3yx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e3yx.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so

# QMI
PRODUCT_COPY_FILES += \
    vendor/samsung/j3ltectc/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so

# RIL
PRODUCT_COPY_FILES += \
    vendor/samsung/j3ltectc/proprietary/lib/libsec-ril-dsds.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsec-ril-dsds.so \
    vendor/samsung/j3ltectc/proprietary/lib/libsec-ril.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsec-ril.so


# Soong Namespaces
PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/j3ltectc
