# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/j7lte-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/j7lte-common/proprietary/bin/msm_irqbalance:$(TARGET_COPY_OUT_SYSTEM)/bin/msm_irqbalance \
    vendor/samsung/j7lte-common/proprietary/etc/B05QL_s5k5e3yx_module_info.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/B05QL_s5k5e3yx_module_info.xml \
    vendor/samsung/j7lte-common/proprietary/etc/T13QL_s5k3l2xx_module_info.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/T13QL_s5k3l2xx_module_info.xml \
    vendor/samsung/j7lte-common/proprietary/lib/hw/audio.primary.msm8916.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/audio.primary.msm8916.so \
    vendor/samsung/j7lte-common/proprietary/lib/hw/camera.vendor.msm8916.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.vendor.msm8916.so \
    vendor/samsung/j7lte-common/proprietary/lib/libAl_Awb.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libAl_Awb.so \
    vendor/samsung/j7lte-common/proprietary/lib/libAl_Awb_Sp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libAl_Awb_Sp.so \
    vendor/samsung/j7lte-common/proprietary/lib/libSamsungMusic_v4.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libSamsungMusic_v4.so \
    vendor/samsung/j7lte-common/proprietary/lib/libSamsungPkcs11Wrapper.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libSamsungPkcs11Wrapper.so \
    vendor/samsung/j7lte-common/proprietary/lib/libSamsungPostProcess.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libSamsungPostProcess.so \
    vendor/samsung/j7lte-common/proprietary/lib/libSamsungPreProcess.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libSamsungPreProcess.so \
    vendor/samsung/j7lte-common/proprietary/lib/libTsAf.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libTsAf.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_DNSe_EP_ver216b.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_DNSe_EP_ver216b.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_DNSe_NRSS_ver230.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_DNSe_NRSS_ver230.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_PreGainBooster_ver104.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_PreGainBooster_ver104.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_SamsungRec_V04013.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SamsungRec_V04013.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_Samsung_Resampler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_Samsung_Resampler.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_SoundAlive_3DPosition_ver107.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SoundAlive_3DPosition_ver107.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_SoundAlive_SRC192_ver205.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SoundAlive_SRC192_ver205.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_SoundAlive_play_plus_ver126a.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SoundAlive_play_plus_ver126a.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_SoundAlive_ver118t.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SoundAlive_ver118t.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_SoundBooster_ver608.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_SoundBooster_ver608.so \
    vendor/samsung/j7lte-common/proprietary/lib/lib_soundaliveresampler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/lib_soundaliveresampler.so \
    vendor/samsung/j7lte-common/proprietary/lib/libaec_algo_front.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaec_algo_front.so \
    vendor/samsung/j7lte-common/proprietary/lib/libaec_algo_rear.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaec_algo_rear.so \
    vendor/samsung/j7lte-common/proprietary/lib/libaf_algo_rear.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaf_algo_rear.so \
    vendor/samsung/j7lte-common/proprietary/lib/libaudioroute.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudioroute.so \
    vendor/samsung/j7lte-common/proprietary/lib/libawb_algo_front_al.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libawb_algo_front_al.so \
    vendor/samsung/j7lte-common/proprietary/lib/libawb_algo_rear_al.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libawb_algo_rear_al.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_common.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_common.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_common_1080p_b.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_common_1080p_b.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_common_1080p_s.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_common_1080p_s.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_common_res0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_common_res0.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_common_res1.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_common_res1.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_common_res2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_common_res2.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_common_res3.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_common_res3.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_default_video.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_default_video.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_golfshot.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_golfshot.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_hfr_1080p_b.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_hfr_1080p_b.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_hfr_1080p_s.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_hfr_1080p_s.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_hfr_120.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_hfr_120.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_liveshot.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_liveshot.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_panorama.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_panorama.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_pip.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_pip.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_preview.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_preview.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_snapshot.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_snapshot.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_uhd_video.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_uhd_video.so \
    vendor/samsung/j7lte-common/proprietary/lib/libchromatix_s5k3l2xx_zslshot.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromatix_s5k3l2xx_zslshot.so \
    vendor/samsung/j7lte-common/proprietary/lib/libface.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libface.so \
    vendor/samsung/j7lte-common/proprietary/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera2_stats_algorithm.so \
    vendor/samsung/j7lte-common/proprietary/lib/libmmcamera_cac2_lib_13M.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_cac2_lib_13M.so \
    vendor/samsung/j7lte-common/proprietary/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/j7lte-common/proprietary/lib/libmysound.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmysound.so \
    vendor/samsung/j7lte-common/proprietary/lib/libsamsungRecord.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungRecord.so \
    vendor/samsung/j7lte-common/proprietary/lib/libsamsungRecord_ns.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungRecord_ns.so \
    vendor/samsung/j7lte-common/proprietary/lib/libsamsungSoundbooster_ext.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungSoundbooster_ext.so \
    vendor/samsung/j7lte-common/proprietary/lib/libsamsungSoundbooster_pgb.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungSoundbooster_pgb.so \
    vendor/samsung/j7lte-common/proprietary/lib/libsamsungVoipResampler.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungVoipResampler.so \
    vendor/samsung/j7lte-common/proprietary/lib/libsamsungearcare.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungearcare.so \
    vendor/samsung/j7lte-common/proprietary/lib/libsamsungeffect.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungeffect.so \
    vendor/samsung/j7lte-common/proprietary/lib/libsamsungpowersound.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsamsungpowersound.so \
    vendor/samsung/j7lte-common/proprietary/lib/libsoundalive.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsoundalive.so \
    vendor/samsung/j7lte-common/proprietary/lib/libtinyalsa.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libtinyalsa.so \
    vendor/samsung/j7lte-common/proprietary/lib/soundfx/libaudioeffectoffload.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libaudioeffectoffload.so \
    vendor/samsung/j7lte-common/proprietary/lib/soundfx/libaudiosa_sec.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libaudiosa_sec.so \
    vendor/samsung/j7lte-common/proprietary/lib/soundfx/libmyspace.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libmyspace.so \
    vendor/samsung/j7lte-common/proprietary/vendor/firmware/libpn548ad_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn548ad_fw.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libactuator_dw9806_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9806_camcorder.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libactuator_dw9806_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9806_camera.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k3l2xx_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2xx_vt.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k3l2xx_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3l2xx_vt_hd.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_common.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_pip.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_pip.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_preview.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_snapshot.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_video.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_vt.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_vt_hd.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_zslshot.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmdsprpc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmdsprpc.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_frame_algorithm.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_is.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_q3a_core.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_q3a_core.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_dw_dw9806b_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dw_dw9806b_eeprom.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_gb_lib.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_image_stab.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_image_stab.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_pdaf.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdaf.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_pdafcamif.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_pdafcamif.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_s5k3l2xx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3l2xx.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_s5k5e3yx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e3yx.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmjpeg.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmjpeg.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libqc-opt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqc-opt.so \
    vendor/samsung/j7lte-common/proprietary/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so
