# Copyright (C) 2017 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/gprimelte/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/gprimelte/proprietary/etc/B05QL_s5k5e3yx_module_info.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/B05QL_s5k5e3yx_module_info.xml \
    vendor/samsung/gprimelte/proprietary/etc/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Bluetooth_cal.acdb \
    vendor/samsung/gprimelte/proprietary/etc/General_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/General_cal.acdb \
    vendor/samsung/gprimelte/proprietary/etc/Global_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Global_cal.acdb \
    vendor/samsung/gprimelte/proprietary/etc/H08QL_s5k4h5yb_module_info.xml:$(TARGET_COPY_OUT_SYSTEM)/etc/H08QL_s5k4h5yb_module_info.xml \
    vendor/samsung/gprimelte/proprietary/etc/Handset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Handset_cal.acdb \
    vendor/samsung/gprimelte/proprietary/etc/Hdmi_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Hdmi_cal.acdb \
    vendor/samsung/gprimelte/proprietary/etc/Headset_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Headset_cal.acdb \
    vendor/samsung/gprimelte/proprietary/etc/Speaker_cal.acdb:$(TARGET_COPY_OUT_SYSTEM)/etc/Speaker_cal.acdb \
    vendor/samsung/gprimelte/proprietary/etc/calib_SI_matrix_data_file.dat:$(TARGET_COPY_OUT_SYSTEM)/etc/calib_SI_matrix_data_file.dat \
    vendor/samsung/gprimelte/proprietary/etc/firmware/nfc_test.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/firmware/nfc_test.bin \
    vendor/samsung/gprimelte/proprietary/etc/sec_s3fwrn5_rfreg.bin:$(TARGET_COPY_OUT_SYSTEM)/etc/sec_s3fwrn5_rfreg.bin \
    vendor/samsung/gprimelte/proprietary/lib/hw/camera.vendor.msm8916.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/camera.vendor.msm8916.so \
    vendor/samsung/gprimelte/proprietary/lib/hw/nfc_nci.msm8916.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/nfc_nci.msm8916.so \
    vendor/samsung/gprimelte/proprietary/lib/hw/sensors.vendor.msm8916.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/sensors.vendor.msm8916.so \
    vendor/samsung/gprimelte/proprietary/lib/libAl_Awb.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libAl_Awb.so \
    vendor/samsung/gprimelte/proprietary/lib/libAl_Awb_Sp.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libAl_Awb_Sp.so \
    vendor/samsung/gprimelte/proprietary/lib/libaec_algo_front.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaec_algo_front.so \
    vendor/samsung/gprimelte/proprietary/lib/libaec_algo_rear.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaec_algo_rear.so \
    vendor/samsung/gprimelte/proprietary/lib/libaf_algo_rear.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaf_algo_rear.so \
    vendor/samsung/gprimelte/proprietary/lib/libalgobsx.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libalgobsx.so \
    vendor/samsung/gprimelte/proprietary/lib/libawb_algo_front_al.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libawb_algo_front_al.so \
    vendor/samsung/gprimelte/proprietary/lib/libawb_algo_rear_al.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libawb_algo_rear_al.so \
    vendor/samsung/gprimelte/proprietary/lib/libmmcamera2_stats_algorithm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera2_stats_algorithm.so \
    vendor/samsung/gprimelte/proprietary/lib/libmmcamera_cac2_lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_cac2_lib.so \
    vendor/samsung/gprimelte/proprietary/lib/libmmcamera_wavelet_lib.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmmcamera_wavelet_lib.so \
    vendor/samsung/gprimelte/proprietary/lib/libsec-ril.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsec-ril.so \
    vendor/samsung/gprimelte/proprietary/vendor/firmware/sec_s3fwrn5_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/sec_s3fwrn5_firmware.bin \
    vendor/samsung/gprimelte/proprietary/vendor/lib/lib-sec-disp.so:$(TARGET_COPY_OUT_VENDOR)/lib/lib-sec-disp.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libactuator_dw9804_e5_camcorder.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9804_e5_camcorder.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libactuator_dw9804_e5_camera.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9804_e5_camera.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_common.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_common_res0.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_common_res0.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_common_res1.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_common_res1.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_default_video.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_liveshot.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_panorama.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_panorama.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_preview.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_snapshot.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_video_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_video_hd.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_zsl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_zsl.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k4h5yb_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k4h5yb_zslshot.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_common.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_pip.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_pip.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_preview.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_snapshot.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_video.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_vt.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_vt_hd.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_vt_hd.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libchromatix_s5k5e3yx_wide_zslshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k5e3yx_wide_zslshot.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libdiag.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdiag.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libdsutils.so:$(TARGET_COPY_OUT_VENDOR)/lib/libdsutils.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libidl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libidl.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_c2d_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_c2d_module.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_cpp_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_cpp_module.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_frame_algorithm.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_frame_algorithm.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_iface_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_iface_modules.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_imglib_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_imglib_modules.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_is.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_is.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_isp_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_isp_modules.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_pproc_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_pproc_modules.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_stats_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_stats_modules.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_vpe_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_vpe_module.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera2_wnr_module.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_wnr_module.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_dw_dw9806b_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dw_dw9806b_eeprom.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_hdr_gb_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_gb_lib.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_hdr_lib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_hdr_lib.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_image_stab.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_image_stab.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_imglib.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imglib.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_lsi_s5k5e3yx_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_lsi_s5k5e3yx_eeprom.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_m24128s_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_m24128s_eeprom.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_rohm_brce064gwz_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_rohm_brce064gwz_eeprom.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_s5k4h5yb.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k4h5yb.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_s5k5e3yx.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k5e3yx.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_silicon_sr544_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_silicon_sr544_eeprom.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_sunny_p12v01m_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sunny_p12v01m_eeprom.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_sunny_p5v23c_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_sunny_p5v23c_eeprom.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_tintless_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_algo.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmcamera_tintless_bg_pca_algo.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_tintless_bg_pca_algo.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmipl.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmipl.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libmmqjpeg_codec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmqjpeg_codec.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/liboemcamera.so:$(TARGET_COPY_OUT_VENDOR)/lib/liboemcamera.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libqcci_legacy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqcci_legacy.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libqmi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libqmi_cci.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_cci.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libqmi_client_qmux.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_client_qmux.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libqmi_common_so.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_common_so.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libqmi_csi.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_csi.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libqmi_encdec.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmi_encdec.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libqmiservices.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqmiservices.so \
    vendor/samsung/gprimelte/proprietary/vendor/lib/libqomx_jpegenc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libqomx_jpegenc.so
