# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/samsung/msm8916-common/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/samsung/msm8916-common/proprietary/bin/adsprpcd:vendor/bin/adsprpcd \
    vendor/samsung/msm8916-common/proprietary/bin/diag_mdlog:vendor/bin/diag_mdlog \
    vendor/samsung/msm8916-common/proprietary/bin/diag_uart_log:vendor/bin/diag_uart_log \
    vendor/samsung/msm8916-common/proprietary/bin/fm_qsoc_patches:vendor/bin/fm_qsoc_patches \
    vendor/samsung/msm8916-common/proprietary/bin/fmconfig:vendor/bin/fmconfig \
    vendor/samsung/msm8916-common/proprietary/bin/ftm_ptt:vendor/bin/ftm_ptt \
    vendor/samsung/msm8916-common/proprietary/bin/irsc_util:vendor/bin/irsc_util \
    vendor/samsung/msm8916-common/proprietary/bin/loc_launcher:vendor/bin/loc_launcher \
    vendor/samsung/msm8916-common/proprietary/bin/mm-qcamera-daemon:vendor/bin/mm-qcamera-daemon \
    vendor/samsung/msm8916-common/proprietary/bin/netmgrd:vendor/bin/netmgrd \
    vendor/samsung/msm8916-common/proprietary/bin/port-bridge:vendor/bin/port-bridge \
    vendor/samsung/msm8916-common/proprietary/bin/ptt_socket_app:vendor/bin/ptt_socket_app \
    vendor/samsung/msm8916-common/proprietary/bin/qcom-system-daemon:vendor/bin/qcom-system-daemon \
    vendor/samsung/msm8916-common/proprietary/bin/qmuxd:vendor/bin/qmuxd \
    vendor/samsung/msm8916-common/proprietary/bin/radish:vendor/bin/radish \
    vendor/samsung/msm8916-common/proprietary/bin/rmt_storage:vendor/bin/rmt_storage \
    vendor/samsung/msm8916-common/proprietary/bin/ssr_diag:vendor/bin/ssr_diag \
    vendor/samsung/msm8916-common/proprietary/bin/ssr_setup:vendor/bin/ssr_setup \
    vendor/samsung/msm8916-common/proprietary/bin/subsystem_ramdump:vendor/bin/subsystem_ramdump \
    vendor/samsung/msm8916-common/proprietary/bin/time_daemon:vendor/bin/time_daemon \
    vendor/samsung/msm8916-common/proprietary/bin/wdsdaemon:vendor/bin/wdsdaemon \
    vendor/samsung/msm8916-common/proprietary/bin/wlandutservice:vendor/bin/wlandutservice \
    vendor/samsung/msm8916-common/proprietary/cameradata/datapattern_420sp.yuv:vendor/cameradata/datapattern_420sp.yuv \
    vendor/samsung/msm8916-common/proprietary/cameradata/datapattern_front_420sp.yuv:vendor/cameradata/datapattern_front_420sp.yuv \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/a300_pfp.fw:vendor/firmware/a300_pfp.fw \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/a300_pm4.fw:vendor/firmware/a300_pm4.fw \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/a420_pfp.fw:vendor/firmware/a420_pfp.fw \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/a420_pm4.fw:vendor/firmware/a420_pm4.fw \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/cpp_firmware_v1_1_1.fw:vendor/firmware/cpp_firmware_v1_1_1.fw \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/cpp_firmware_v1_1_6.fw:vendor/firmware/cpp_firmware_v1_1_6.fw \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/cpp_firmware_v1_2_0.fw:vendor/firmware/cpp_firmware_v1_2_0.fw \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/cpp_firmware_v1_4_0.fw:vendor/firmware/cpp_firmware_v1_4_0.fw \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/ice40.bin:vendor/firmware/ice40.bin \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/leia_pfp_470.fw:vendor/firmware/leia_pfp_470.fw \
    vendor/samsung/msm8916-common/proprietary/etc/firmware/leia_pm4_470.fw:vendor/firmware/leia_pm4_470.fw \
    vendor/samsung/msm8916-common/proprietary/etc/plmn_delta.bin:vendor/etc/plmn_delta.bin \
    vendor/samsung/msm8916-common/proprietary/etc/plmn_se13.bin:vendor/etc/plmn_se13.bin \
    vendor/samsung/msm8916-common/proprietary/etc/somxreg.conf:vendor/etc/somxreg.conf \
    vendor/samsung/msm8916-common/proprietary/etc/srm.bin:vendor/etc/srm.bin \
    vendor/samsung/msm8916-common/proprietary/lib/libOmxVdecHevc.so:vendor/lib/libOmxVdecHevc.so \
    vendor/samsung/msm8916-common/proprietary/lib/libatparser.so:vendor/lib/libatparser.so \
    vendor/samsung/msm8916-common/proprietary/lib/libaudio-ril.so:vendor/lib/libaudio-ril.so \
    vendor/samsung/msm8916-common/proprietary/lib/libcordon.so:vendor/lib/libcordon.so \
    vendor/samsung/msm8916-common/proprietary/lib/libdrmdecrypt.so:vendor/lib/libdrmdecrypt.so \
    vendor/samsung/msm8916-common/proprietary/lib/libedmnativehelper.so:vendor/lib/libedmnativehelper.so \
    vendor/samsung/msm8916-common/proprietary/lib/libexifa.so:vendor/lib/libexifa.so \
    vendor/samsung/msm8916-common/proprietary/lib/libfactoryutil.so:vendor/lib/libfactoryutil.so \
    vendor/samsung/msm8916-common/proprietary/lib/libgdmcprov.so:vendor/lib/libgdmcprov.so \
    vendor/samsung/msm8916-common/proprietary/lib/libhdcp2.so:vendor/lib/libhdcp2.so \
    vendor/samsung/msm8916-common/proprietary/lib/libjpega.so:vendor/lib/libjpega.so \
    vendor/samsung/msm8916-common/proprietary/lib/libmmcamera_interface.so:vendor/lib/libmmcamera_interface.so \
    vendor/samsung/msm8916-common/proprietary/lib/libmmjpeg_interface.so:vendor/lib/libmmjpeg_interface.so \
    vendor/samsung/msm8916-common/proprietary/lib/libomission_avoidance.so:vendor/lib/libomission_avoidance.so \
    vendor/samsung/msm8916-common/proprietary/lib/libplayready_v2.5.so:vendor/lib/libplayready_v2.5.so \
    vendor/samsung/msm8916-common/proprietary/lib/libqomx_core.so:vendor/lib/libqomx_core.so \
    vendor/samsung/msm8916-common/proprietary/lib/libseckeyprov.so:vendor/lib/libseckeyprov.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsecnativefeature.so:vendor/lib/libsecnativefeature.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsecril-client.so:vendor/lib/libsecril-client.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomx263dsw.so:vendor/lib/libsomx263dsw.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomx264dsw.so:vendor/lib/libsomx264dsw.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxaacd.so:vendor/lib/libsomxaacd.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxaace.so:vendor/lib/libsomxaace.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxadpcmd.so:vendor/lib/libsomxadpcmd.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxamrd.so:vendor/lib/libsomxamrd.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxcmn.so:vendor/lib/libsomxcmn.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxcore.so:vendor/lib/libsomxcore.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxflacd.so:vendor/lib/libsomxflacd.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxhevcdsw.so:vendor/lib/libsomxhevcdsw.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxmp3d.so:vendor/lib/libsomxmp3d.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxmp4vdsw.so:vendor/lib/libsomxmp4vdsw.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxnaace.so:vendor/lib/libsomxnaace.so \
    vendor/samsung/msm8916-common/proprietary/lib/libsomxvp8d.so:vendor/lib/libsomxvp8d.so \
    vendor/samsung/msm8916-common/proprietary/vendor/bin/thermal-engine:vendor/bin/thermal-engine \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/com.qualcomm.qti.bluetooth_audio@1.0_vendor.so:vendor/lib/com.qualcomm.qti.bluetooth_audio@1.0_vendor.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/drm/libdrmprplugin.so:vendor/lib/drm/libdrmprplugin.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/drm/libdrmwvmplugin.so:vendor/lib/drm/libdrmwvmplugin.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/eglSubDriverAndroid.so:vendor/lib/egl/eglSubDriverAndroid.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/eglsubAndroid.so:vendor/lib/egl/eglsubAndroid.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libEGL_adreno.so:vendor/lib/egl/libEGL_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libESXEGL_adreno.so:vendor/lib/egl/libESXEGL_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libESXGLESv1_CM_adreno.so:vendor/lib/egl/libESXGLESv1_CM_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libESXGLESv2_adreno.so:vendor/lib/egl/libESXGLESv2_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libGLESv1_CM_adreno.so:vendor/lib/egl/libGLESv1_CM_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libGLESv2_adreno.so:vendor/lib/egl/libGLESv2_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libQTapGLES.so:vendor/lib/egl/libQTapGLES.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libRBEGL_adreno.so:vendor/lib/egl/libRBEGL_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libRBGLESv1_CM_adreno.so:vendor/lib/egl/libRBGLESv1_CM_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libRBGLESv2_adreno.so:vendor/lib/egl/libRBGLESv2_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/egl/libq3dtools_adreno.so:vendor/lib/egl/libq3dtools_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/hw/android.hardware.bluetooth@1.0-impl-qti.so:vendor/lib/hw/android.hardware.bluetooth@1.0-impl-qti.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/hw/flp.default.so:vendor/lib/hw/flp.default.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/hw/vendor.qti.hardware.fm@1.0-impl.so:vendor/lib/hw/vendor.qti.hardware.fm@1.0-impl.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libC2D2.so:vendor/lib/libC2D2.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libCB.so:vendor/lib/libCB.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libExtendedExtractor.so:vendor/lib/libExtendedExtractor.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libFlacSwDec.so:vendor/lib/libFlacSwDec.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libI420colorconvert.so:vendor/lib/libI420colorconvert.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libOmxAacDec.so:vendor/lib/libOmxAacDec.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libOmxEvrcDec.so:vendor/lib/libOmxEvrcDec.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libOmxQcelp13Dec.so:vendor/lib/libOmxQcelp13Dec.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libOpenCL.so:vendor/lib/libOpenCL.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libRSDriver_adreno.so:vendor/lib/libRSDriver_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libSubSystemShutdown.so:vendor/lib/libSubSystemShutdown.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libTimeService.so:vendor/lib/libTimeService.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libWVStreamControlAPI_L1.so:vendor/lib/libWVStreamControlAPI_L1.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libacdb-fts.so:vendor/lib/libacdb-fts.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libacdbloader.so:vendor/lib/libacdbloader.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libacdbmapper.so:vendor/lib/libacdbmapper.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libacdbrtac.so:vendor/lib/libacdbrtac.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libadiertac.so:vendor/lib/libadiertac.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libadreno_utils.so:vendor/lib/libadreno_utils.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libadsprpc.so:vendor/lib/libadsprpc.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libaptXHD_encoder.so:vendor/lib/libaptXHD_encoder.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libaptX_encoder.so:vendor/lib/libaptX_encoder.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libaudcal.so:vendor/lib/libaudcal.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libbccQTI.so:vendor/lib/libbccQTI.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libc2d30-a3xx.so:vendor/lib/libc2d30-a3xx.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libc2d30-a4xx.so:vendor/lib/libc2d30-a4xx.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libconfigdb.so:vendor/lib/libconfigdb.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libdisp-aba.so:vendor/lib/libdisp-aba.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libdrmfs.so:vendor/lib/libdrmfs.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libdrmtime.so:vendor/lib/libdrmtime.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libfastcvopt.so:vendor/lib/libfastcvopt.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libflp.so:vendor/lib/libflp.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libgeofence.so:vendor/lib/libgeofence.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libgsl.so:vendor/lib/libgsl.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libhwdaphal.so:vendor/lib/libhwdaphal.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libizat_core.so:vendor/lib/libizat_core.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libjpegdhw.so:vendor/lib/libjpegdhw.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libjpegehw.so:vendor/lib/libjpegehw.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/liblbs_core.so:vendor/lib/liblbs_core.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/liblistensoundmodel2.so:vendor/lib/liblistensoundmodel2.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libllvm-glnext.so:vendor/lib/libllvm-glnext.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libllvm-qcom.so:vendor/lib/libllvm-qcom.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmdmdetect.so:vendor/lib/libmdmdetect.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmm-abl-oem.so:vendor/lib/libmm-abl-oem.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmm-abl.so:vendor/lib/libmm-abl.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmm-als.so:vendor/lib/libmm-als.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmm-color-convertor.so:vendor/lib/libmm-color-convertor.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmm-disp-apis.so:vendor/lib/libmm-disp-apis.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmm-hdcpmgr.so:vendor/lib/libmm-hdcpmgr.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmm-qdcm.so:vendor/lib/libmm-qdcm.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmmQSM.so:vendor/lib/libmmQSM.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmmcamera_faceproc.so:vendor/lib/libmmcamera_faceproc.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmmparser.so:vendor/lib/libmmparser.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libmmrtpdecoder.so:vendor/lib/libmmrtpdecoder.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libnetmgr.so:vendor/lib/libnetmgr.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/liboemcrypto.so:vendor/lib/liboemcrypto.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libperipheral_client.so:vendor/lib/libperipheral_client.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libprdrmdecrypt.so:vendor/lib/libprdrmdecrypt.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libqomx_jpegdec.so:vendor/lib/libqomx_jpegdec.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libril-qcril-hook-oem.so:vendor/lib/libril-qcril-hook-oem.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/librpmb.so:vendor/lib/librpmb.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/librs_adreno.so:vendor/lib/librs_adreno.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/librs_adreno_sha1.so:vendor/lib/librs_adreno_sha1.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libsc-a2xx.so:vendor/lib/libsc-a2xx.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libsc-a3xx.so:vendor/lib/libsc-a3xx.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libscale.so:vendor/lib/libscale.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libscve.so:vendor/lib/libscve.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libscve_mv.so:vendor/lib/libscve_mv.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libsd_sdk_display.so:vendor/lib/libsd_sdk_display.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libssd.so:vendor/lib/libssd.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libstlport.so:vendor/lib/libstlport.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libsubsystem_control.so:vendor/lib/libsubsystem_control.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libthermalclient.so:vendor/lib/libthermalclient.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libthermalioctl.so:vendor/lib/libthermalioctl.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libtzdrmgenprov.so:vendor/lib/libtzdrmgenprov.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libtzplayready.so:vendor/lib/libtzplayready.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libwvdrm_L1.so:vendor/lib/libwvdrm_L1.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libwvm.so:vendor/lib/libwvm.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/libxml.so:vendor/lib/libxml.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/mediadrm/libprmediadrmdecrypt.so:vendor/lib/mediadrm/libprmediadrmdecrypt.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/mediadrm/libprmediadrmplugin.so:vendor/lib/mediadrm/libprmediadrmplugin.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/mediadrm/libwvdrmengine.so:vendor/lib/mediadrm/libwvdrmengine.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/soundfx/libqcbassboost.so:vendor/lib/soundfx/libqcbassboost.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/soundfx/libqcreverb.so:vendor/lib/soundfx/libqcreverb.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/soundfx/libqcvirt.so:vendor/lib/soundfx/libqcvirt.so \
    vendor/samsung/msm8916-common/proprietary/vendor/lib/vendor.qti.hardware.fm@1.0_vendor.so:vendor/lib/vendor.qti.hardware.fm@1.0_vendor.so \
    vendor/samsung/msm8916-common/proprietary/vendor/media/LMspeed_508.emd:vendor/media/LMspeed_508.emd \
    vendor/samsung/msm8916-common/proprietary/vendor/media/PFFprec_600.emd:vendor/media/PFFprec_600.emd

PRODUCT_PACKAGES += \
    libloc_api_v02 \
    libloc_ds_api \
    vendor.qti.hardware.fm@1.0 \
    libHevcSwDecoder \
    libaudioalsa \
    libbtnv \
    libqct_resampler \
    libtime_genoff \
    TimeService
