# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/j5ltechn/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/j5ltechn

PRODUCT_COPY_FILES += \
    vendor/samsung/j5ltechn/proprietary/lib/hw/sensors.vendor.msm8916.so:$(TARGET_COPY_OUT_SYSTEM)/lib/hw/sensors.vendor.msm8916.so \
    vendor/samsung/j5ltechn/proprietary/lib/libsec-ril-dsds.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsec-ril-dsds.so \
    vendor/samsung/j5ltechn/proprietary/lib/libsec-ril.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libsec-ril.so \
    vendor/samsung/j5ltechn/proprietary/vendor/firmware/libpn548ad_fw.so:$(TARGET_COPY_OUT_VENDOR)/firmware/libpn548ad_fw.so
