# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/j5-common/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifneq ($(filter j5lte j5ltechn j5nlte j53gxx,$(TARGET_DEVICE)),)

endif
